apiVersion: v1
kind:  PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    app: pvc
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessMode:
     ReadWriteOnce
  resources:
    requests:
      storage: 4Gi