apiVersion: v1
kind: service
metadata:
   name: clusterip
   labels:
     app: clusterip
spec:
   selector:
      app: nginx
   port:
    - protocol: TCP
      port: 80
   type: ClusterIp
